# Generated by Django 4.2.10 on 2024-04-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mycustomuser',
            managers=[
            ],
        ),
    ]
