# Generated by Django 4.2.10 on 2024-02-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_session', '0002_courses_remove_usercourses_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
