# Generated by Django 4.2.10 on 2024-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0005_alter_courses_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
